INSERT INTO public.tb_cursos (desc_curso, modalidade_curso, turno_curso)
VALUES ('ADMINISTRAÇÃO', 0, 0),
('ADMINISTRAÇÃO', 0, 2),
('ARQUITETURA E URBANISMO', 0, 3),
('ARTES VISUAIS', 0, 0),
('BIOMEDICINA', 0, 3),
('CIÊNCIA DA COMPUTAÇÃO', 0, 3),
('CIÊNCIAS BIOLÓGICAS', 0, 0),
('CIÊNCIAS BIOLÓGICAS', 0, 2),
('CIÊNCIAS CONTÁBEIS', 0, 2),
('CIÊNCIAS ECONÔMICAS', 0, 0),
('CIÊNCIAS ECONÔMICAS', 0, 2),
('CIÊNCIAS SOCIAIS', 0, 0),
('COMUNICAÇÃO SOCIAL', 0, 3),
('DESIGN DE PRODUTO', 0, 0),
('DESIGN GRÁFICO', 0, 3),
('DIREITO', 0, 0),
('DIREITO', 0, 2),
('EDUCAÇÃO FÍSICA', 0, 3),
('ENFERMAGEM', 0, 3),
('ENGENHARIA AGRONÔMICA', 0, 3),
('ENGENHARIA AMBIENTAL', 0, 3),
('ENGENHARIA CARTOGRÁFICA E DE AGRIMENSURA', 0, 3),
('ENGENHARIA CIVIL', 0, 3),
('ENGENHARIA DE BIOPROCESSOS E BIOTECNOLOGIA', 0, 3),
('ENGENHARIA DE ENERGIA', 0, 0),
('ENGENHARIA DE PRODUÇÃO', 0, 3),
('ENGENHARIA ELÉTRICA', 0, 3),
('ENGENHARIA ELÉTRICA', 0, 2),
('ENGENHARIA FLORESTAL', 0, 3),
('ENGENHARIA INDUSTRIAL MADEIREIRA', 0, 3),
('ENGENHARIA INDUSTRIAL MADEIREIRA', 0, 2),
('ENGENHARIA MECÂNICA', 0, 3),
('ENGENHARIA MECÂNICA', 0, 2),
('ENGENHARIA QUÍMICA', 0, 3),
('ESTATÍSTICA', 0, 2),
('EXPRESSÃO GRÁFICA', 0, 3),
('EXPRESSÃO GRÁFICA', 0, 0),
('FARMÁCIA', 0, 3),
('FILOSOFIA', 0, 0),
('TECNOLOGIA EM ANÁLISE E DESENVOLVIMENTO DE SISTEMAS', 0, 2),
('TECNOLOGIA EM ANÁLISE E DESENVOLVIMENTO DE SISTEMAS', 0, 1);

INSERT INTO public.tb_competencias
(desc_competencia)
VALUES 
  ('Java'),
  ('Python'),
  ('C++'),
  ('Trabalho em equipe'),
  ('Comunicação eficaz'),
  ('Liderança'),
  ('Resolução de problemas'),
  ('HTML/CSS'),
  ('JavaScript'),
  ('Adaptabilidade'),
  ('Empatia'),
  ('Gestão de tempo'),
  ('Relacionamento interpessoal'),
  ('Inovação'),
  ('Negociação'),
  ('Machine Learning'),
  ('Pensamento analítico'),
  ('Ruby'),
  ('SQL'),
  ('Inteligência emocional'),
  ('Angular'),
  ('Trabalho sob pressão'),
  ('Comunicação escrita'),
  ('React'),
  ('Trabalho em grupo'),
  ('Autoconfiança'),
  ('Habilidade de aprendizado rápido'),
  ('Node.js'),
  ('Resiliência'),
  ('Colaboração');